# Generated by Django 5.0.7 on 2024-08-09 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_auther_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
