# Generated by Django 5.0.7 on 2024-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_author_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pic',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
