# Generated by Django 5.0.7 on 2024-08-09 10:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_author_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='cap',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date',
        ),
        migrations.RemoveField(
            model_name='author',
            name='pic',
        ),
        migrations.AddField(
            model_name='book',
            name='cap',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
